ElearningWithMvc/Models/AllCourse.cs
namespace ElearningWithMvc.Models
{
	public class AllCourse
	{
        
            public List<AddCourse> Course { get; set; }
            public List<CourseVideo> AddSubCourse { get; set; }
        
    }
}

ElearningWithMvc/Controllers/UserdashboardController.cs
using ElearningWithMvc.Context;
using ElearningWithMvc.Migrations;
using ElearningWithMvc.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Org.BouncyCastle.Asn1.X509;
using Razorpay.Api;
using static ElearningWithMvc.Models.AllCourse;

namespace ElearningWithMvc.Controllers
{
	public class UserdashboardController : Controller
	{
		private readonly ApplicationDbContext db;
          private readonly string _keyId = "rzp_test_4DrJJevYZkd0No";
        private readonly string _keySecret = "3oX1Dvxlpy2wB3BGnDPxGtH8";
		public UserdashboardController(ApplicationDbContext db) 
		{
			this.db = db;
		}

		public IActionResult Index()
		{
			var topCourses = db.AddCourses.OrderBy(c => c.CourseId).Take(5).ToList();
			return View(topCourses);
			
		}

		public IActionResult Userhome()
		{
			return View();
		}

		public IActionResult AllCourse()
		{
            var topCourses = db.AddCourses.ToList();
            return View(topCourses);
           
		}

		public IActionResult About()
		{
			return View();
		}


       

        public IActionResult MyCourse()
        {
           var email = HttpContext.Session.GetString("Email");
           var data =  db.AddSubCourse.FromSqlRaw($"exec fetchmycourse '{email}'").ToList();
           
           return View(data);
        }

        public IActionResult WatchVideo(int id)
        {
            var data = db.SubcourseVideo.FromSqlRaw($"exec fatchvideo {id}").ToList();
            return View(data); 
        }



        //[HttpPost]
        //public IActionResult Cart(int[] id , AddToCart a)
        //{

        //       var user = HttpContext.Session.GetString("Username");

        //        foreach (var b in id)
        //        {
        //            var cartItem = new AddToCart
        //            {
        //                CourseId = id,
        //                CourseName = id.CourseName,
        //                InstructorName = model.InstructorName,
        //                CourseImage = model.CourseImage,
        //                Price = model.Price,
        //                Suser = user,
        //                SubCourse = SubCourse[i],
        //                VideoTitle = VideoTitle[i],
        //                VideoUrl = VideoUrl[i], 
        //                Quantity = model.Quantity 
        //            };

        //            db.AddToCart.Add(cartItem);
        //        }

        //        db.SaveChanges();





        //    return View(model);
        //}


        //public IActionResult Details(int id)
        //{
        //    var course = db.AddCourses.Where(x=>x.CourseId == id).ToList();
        //    if (course == null)
        //    {
        //        return NotFound();
        //    }
        //    var coursename = course.First().CourseId;
        //    var courseVideos = db.AddSubCourse.Where(v => v.CourseId == coursename).ToList();

        //    var viewModel = new AllCourse
        //    {
        //        Course = course.ToList(),
        //        AddSubCourse = courseVideos
        //    };

        //    return View(viewModel);
        //}

        public IActionResult Details(int id)
        {
            var data = db.AddSubCourse.Where(x=>x.SubCourseId == id).ToList();
            return View(data);
        }

        public IActionResult ByNow(int id)
        {
            var data = db.AddSubCourse.Find(id);
            var amount = data.price;
            ViewBag.totalprice = amount;

             HttpContext.Session.SetInt32("SubcourseId", id);
            var options = new Dictionary<string, object>
            {
                { "amount", amount * 100 },  // Amount in paise
                { "currency", "INR" },
                { "receipt", "order_rcptid_" + DateTime.Now.Ticks },
                { "payment_capture", 1 }
            };
            var _keyId = "rzp_test_hyxzlMmdpXpNKr";
            var _keySecret = "GWmkim1me8JM0XvpIucQwGCx";


			var client = new RazorpayClient(_keyId, _keySecret);
            var razorpayOrder = client.Order.Create(options);
            ViewBag.razorpayOrder = razorpayOrder["id"];
            ViewBag.Key = _keyId;
            return View("Checkout");
        }
        public IActionResult SubCourseList(int id)
        {
            var courses = db.AddCourses.Where(x => x.CourseId == id).ToList();
            if (courses == null || !courses.Any())
            {
                return NotFound();
            }
            var coursename = courses.First().CourseId;
            //var course = db.AddCourses.Find
            var courseVideos = db.AddSubCourse.Where(v => v.CourseId == coursename).ToList();

            var viewModel = new AllCourse
            {
                Course = courses.ToList(),
                AddSubCourse = courseVideos
            };

            return View(viewModel);
        }

        public IActionResult Successpayment()
        {
            int subcourseId = Convert.ToInt32(HttpContext.Session.GetInt32("SubcourseId").ToString());
            var UserEmail = HttpContext.Session.GetString("Email");
            var data = new PaymentDone
            {
               SubCourseId = subcourseId ,
               UserEmail = UserEmail 
            };
            db.PaymentDone.Add(data);
            db.SaveChanges();
            return RedirectToAction("AllCourse");
        }
    }
}

ElearningWithMvc/Views/Userdashboard/About.cshtml
<link rel="stylesheet" type="text/css" href="/Content/mysitecss/about.css">
<link rel="stylesheet" type="text/css" href="/Content/mysitecss/about_responsive.css">


<div class="home" style="margin-top:150px">
@* 	<!-- Background image artist https://unsplash.com/@thepootphotographer --> *@
	<div class="home_background parallax_background parallax-window" data-parallax="scroll" data-image-src="/Content/images/about.jpg" data-speed="0.8"></div>
	<div class="home_container">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="home_content text-center">
						<div class="home_title">About us</div>
						<div class="breadcrumbs">
							<ul>
								<li><a asp-controller="Userdashboard" asp-action="Index">Home</a></li>
								<li>About us</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- About -->

<div class="about">
	<div class="container">
		<div class="row about_row row-lg-eq-height">
			<div class="col-lg-6">
				<div class="about_content">
					<div class="about_title">Our Platform's main goal</div>
					<div class="about_text">
						<p>Suspendisse tincidunt magna eget massa hendrerit efficitur. Ut euismod pellentesque imperdiet. Cras laoreet gravida lectus, at viverra lorem venenatis in. Aenean id varius quam. Nullam bibendum interdum dui, ac tempor lorem convallis ut. Maecenas rutrum viverra sapien sed fermentum. Morbi tempor odio eget lacus tempus pulvinar. Praesent vel nisl fermentum, gravida augue. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id convallis libero, sed blandit nibh. Nam ultricies tristique nibh, consequat ornare nibh. Quisque vitae odio ligula.</p>
					</div>
				</div>
			</div>
			<div class="col-lg-6">
				<div class="about_image"><img src="/Content/images/about_1.jpg"></div>
			</div>
		</div>
		<div class="row about_row row-lg-eq-height">
			<div class="col-lg-6 order-lg-1 order-2">
				<div class="about_image"><img src="/Content/images/elearn.jpg" alt=""></div>
			</div>
			<div class="col-lg-6 order-lg-2 order-1">
				<div class="about_content">
					<div class="about_title">eLearn's Vision</div>
					<div class="about_text">
						<p>Suspendisse tincidunt magna eget massa hendrerit efficitur. Ut euismod pellentesque imperdiet. Cras laoreet gravida lectus, at viverra lorem venenatis in. Aenean id varius quam. Nullam bibendum interdum dui, ac tempor lorem convallis ut. Maecenas rutrum viverra sapien sed fermentum. Morbi tempor odio eget lacus tempus pulvinar. Praesent vel nisl fermentum, gravida augue. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id convallis libero, sed blandit nibh. Nam ultricies tristique nibh.</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>







<!-- Teachers -->

<div class="teachers">
	<div class="container">
		<div class="row">
			<div class="col">
				<div class="teachers_title text-center">Meet the Teachers</div>
			</div>
		</div>
		<div class="row teachers_row">

			<!-- Teacher -->
			<div class="col-lg-4 col-md-6">
				<div class="teacher">
					<div class="teacher_image"><img src="/Content/images/teacher_1.jpg"></div>
					<div class="teacher_body text-center">
						<div class="teacher_title"><a href="#">Jonathan Smith</a></div>
						<div class="teacher_subtitle">Marketing</div>
						<div class="teacher_social">
							<ul>
								<li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
								<li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
								<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>

			<!-- Teacher -->
			<div class="col-lg-4 col-md-6">
				<div class="teacher">
					<div class="teacher_image"><img src="/Content/images/teacher_2.jpg"></div>
					<div class="teacher_body text-center">
						<div class="teacher_title"><a href="#">Michelle Williams</a></div>
						<div class="teacher_subtitle">Art & Design</div>
						<div class="teacher_social">
							<ul>
								<li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
								<li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
								<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>

			<!-- Teacher -->
			<div class="col-lg-4 col-md-6">
				<div class="teacher">
					<div class="teacher_image"><img src="/Content/images/teacher_3.jpg"></div>
					<div class="teacher_body text-center">
						<div class="teacher_title"><a href="#">Jack Gallagan</a></div>
						<div class="teacher_subtitle">Marketing</div>
						<div class="teacher_social">
							<ul>
								<li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
								<li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
								<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>

			<!-- Teacher -->
			<div class="col-lg-4 col-md-6">
				<div class="teacher">
					<div class="teacher_image"><img src="/Content/images/teacher_4.jpg"></div>
					<div class="teacher_body text-center">
						<div class="teacher_title"><a href="#">Christinne Smith</a></div>
						<div class="teacher_subtitle">Marketing</div>
						<div class="teacher_social">
							<ul>
								<li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
								<li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
								<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>

			<!-- Teacher -->
			<div class="col-lg-4 col-md-6">
				<div class="teacher">
					<div class="teacher_image"><img src="/Content/images/teacher_5.jpg"></div>
					<div class="teacher_body text-center">
						<div class="teacher_title"><a href="#">Michelle Williams</a></div>
						<div class="teacher_subtitle">Art & Design</div>
						<div class="teacher_social">
							<ul>
								<li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
								<li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
								<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>

			<!-- Teacher -->
			<div class="col-lg-4 col-md-6">
				<div class="teacher">
					<div class="teacher_image"><img src="/Content/images/teacher_6.jpg"></div>
					<div class="teacher_body text-center">
						<div class="teacher_title"><a href="#">Jack Gallagan</a></div>
						<div class="teacher_subtitle">Marketing</div>
						<div class="teacher_social">
							<ul>
								<li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
								<li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
								<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>

		</div>

	</div>
</div>

ElearningWithMvc/Views/Userdashboard/AllCourse.cshtml
@model List<AddCourse>


<div class="container mt-5">
    <h2 style="text-align:center;margin-top:100px;font-weight:bold">Latest Courses and Videos</h2>
    <div class="row justify-content-center mb-3">
        <div class="col-md-12 col-xl-10">
            @foreach (var item in Model)
            {
                <div class="card shadow-0 border rounded-3 mb-4">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12 col-lg-3 col-xl-3 mb-4 mb-lg-0">
                                <div class="bg-image hover-zoom ripple rounded ripple-surface">
                                    <img src="@item.CourseImage" class="w-100" />
                                    <a href="your-url.html">
                                        <div class="hover-overlay">
                                            <div class="mask" style="background-color: rgba(253, 253, 253, 0.15);"></div>
                                        </div>
                                    </a>
                                </div>
                            </div>
                            <div class="col-md-6 col-lg-6 col-xl-6">
                                <h5>@item.CourseName</h5>
                                <div class="mt-1 mb-0 text-muted small">
                                    <span>@item.InstructorName</span>
                                </div>
                               @*  <p class="text-truncate mb-4 mb-md-0">
                                    @item.Descripation<br />
                                </p> *@
                            </div>

                            <div class="col-md-6 col-lg-3 col-xl-3 border-sm-start-none border-start">
                                @* <div class="d-flex flex-row align-items-center mb-1">
                                    <h4 class="mb-1 me-1">Price</h4>
                                    <span class="text-danger">₹ @item.Price</span>
                                </div> *@
                                <h6 class="text-success">Special Offer</h6>
                                <div class="d-flex flex-column mt-4">
                                    <a asp-controller="Userdashboard" asp-action="SubCourseList"  asp-route-id="@item.CourseId" class="btn btn-warning">Course List</a>

                                    <button class="btn btn-outline-danger mt-2" type="button">Add to wishlist</button>
                                </div>
                            </div>



                        </div>
                    </div>
                </div>
            }
        </div>
    </div>

    
    </div>

ElearningWithMvc/Views/Userdashboard/Checkout.cshtml
@{
    ViewData["Title"] = "Checkout";
}

<!DOCTYPE html>
<html>
<head>
    <title>Checkout</title>
    <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
</head>
<body>
    <h1>Checkout</h1>
    <script type="text/javascript">
        var options = {
            "key": "@ViewBag.Key", // Enter the Key ID generated from the Dashboard
            "amount": @ViewBag.totalprice + "00", // Amount in paise
            "currency": "INR",
            "name": "Your Company Name",
            "description": "Order Payment",
            "order_id": "@ViewBag.razorpayOrder", // Order ID created in the server
            "handler": function (response) {
                // Handle the payment response
                console.log(response);
                window.location.href = '/Userdashboard/Successpayment';
            },
            "prefill": {
                "name": "",
                "email": "",
                "contact": ""
            },
            "theme": {
                "color": "#3399cc"
            }
        };
        var rzp1 = new Razorpay(options);
        rzp1.open();
    </script>
</body>
</html>

ElearningWithMvc/Views/Userdashboard/Details.cshtml
@model List<CourseVideo>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous" />

<div style="margin-top: 200px"></div>
<div class="container">
    @foreach (var a in Model)
    {     
    <div class="row">
        <div class="col-md-7">
            <div class="project-info-box mt-0">
                <h5>COURSE DETAILS</h5>
                <p class="mb-0">
                  
                </p>
            </div>

            <div class="project-info-box">
                <p><b>Course:</b> <span id="courseName" class="font-weight-bold" style="color: #ff8a00;">@a.Subcourse</span></p>
                <p><b>Level:</b> <span id="topicName" class="font-weight-bold" style="color: #ff8a00;">@a.Level</span></p>
                <p><b>Provider:</b> E-Learning</p>
                <p class="mb-0"><b>Price:</b> ₹ <span id="price" class="font-weight-bold" style="color: Green;">@a.price</span></p>
                <p><b>Description:</b> <span id="subCourseName" class="font-weight-bold" style="color: #dc3545;">@a.Description  </span></p>
            </div>

            <div class="project-info-box mt-2 mb-0">
                <p class="mb-0">
                    <span class="font-weight-bold mr-10 align-middle d-none d-md-inline">Share:</span>
                    <a class="btn text-white" data-mdb-ripple-init style="background-color: #3b5998;" href="#!" role="button">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                    <a class="btn text-white" data-mdb-ripple-init style="background-color: #55acee;" href="#!" role="button">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a class="btn text-white" data-mdb-ripple-init style="background-color: #c61118;" href="#!" role="button">
                        <i class="fab fa-pinterest"></i>
                    </a>
                    <a class="btn text-white" data-mdb-ripple-init style="background-color: #0082ca;" href="#!" role="button">
                        <i class="fab fa-linkedin-in"></i>
                    </a>
                </p>
            </div>
        </div>

        <div class="col-md-5">    
            <img src="@a.SubCourseImage" class="rounded" width="420" height="270" />
            <div class="project-info-box">
                <a> <input id="addToCart" asp-controller="Userdashboard" asp-action="AddToCart"  asp-route-id="@a.CourseId" class="btn btn-warning btn-block col-md-11 mt-3" type="submit" value="Add To Cart" /></a>
                <button class="btn btn-outline-danger mt-2 btn-block col-md-11" type="button">Add to Wishlist</button>
            </div>
        </div>
    </div>
    }
</div>
<div style="margin-top: 50px"></div>

ElearningWithMvc/Views/Userdashboard/Index.cshtml
@using ElearningWithMvc.Migrations
@model List<AddCourse>

<style>
	.video_container {
		position: relative;
		width: 100%;
		padding-bottom: 56.25%; /* 16:9 aspect ratio */
		height: 0;
	}

		.video_container iframe {
			position: absolute;
			top: 0;
			left: 0;
			width: 100%;
			height: 100%;
		}
</style>

<!-- Home -->

<div class="home">
	<div class="home_slider_container">

		<!-- Home Slider -->
		<div class="owl-carousel owl-theme home_slider">

			<!-- Slider Item -->
			<div class="owl-item">
				@* <!-- Background image artist https://unsplash.com/@benwhitephotography --> *@
				<div class="home_slider_background" style="background-image:url(/Content/images/index.jpg)"></div>
				<div class="home_container">
					<div class="container">
						<div class="row">
							<div class="col">
								<div class="home_content text-center">
									<div class="home_logo"><img src="~/Content/Images/home_logo.png" alt=""></div>
									<div class="home_text">
										<div class="home_title">Complete Online Courses</div>
										<div class="home_subtitle">Maecenas rutrum viverra sapien sed fermentum. Morbi tempor odio eget lacus tempus pulvinar. Praesent vel nisl fermentum, gravida augue ut, fermentum ipsum.</div>
									</div>
									<div class="home_buttons">
										<div class="button home_button"><a href="About.aspx">learn more<div class="button_arrow"><i class="fa fa-angle-right" aria-hidden="true"></i></div></a></div>
										<div class="button home_button"><a href="allCourses.aspx">see all courses<div class="button_arrow"><i class="fa fa-angle-right" aria-hidden="true"></i></div></a></div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

			<!-- Slider Item -->
			<div class="owl-item">
				@* <!-- Background image artist https://unsplash.com/@benwhitephotography --> *@
				<div class="home_slider_background" style="background-image:url(/Content/Images/index.jpg)"></div>
				<div class="home_container">
					<div class="container">
						
						<div class="row">
							<div class="col">
								<div class="home_content text-center">
									<div class="home_logo"><img src="~/Content/Images/logo.png" alt=""></div>
									<div class="home_text">
										<div class="home_title">Complete Online Courses</div>
										<div class="home_subtitle">Maecenas rutrum viverra sapien sed fermentum. Morbi tempor odio eget lacus tempus pulvinar. Praesent vel nisl fermentum, gravida augue ut, fermentum ipsum.</div>
									</div>
									<div class="home_buttons">
										<div class="button home_button"><a href="#">learn more<div class="button_arrow"><i class="fa fa-angle-right" aria-hidden="true"></i></div></a></div>
										<div class="button home_button"><a href="#">see all courses<div class="button_arrow"><i class="fa fa-angle-right" aria-hidden="true"></i></div></a></div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

			<!-- Slider Item -->
			<div class="owl-item">
				@* <!-- Background image artist https://unsplash.com/@benwhitephotography --> *@
				<div class="home_slider_background" style="background-image:url(/Content/Images/index.jpg)"></div>
				<div class="home_container">
					<div class="container">
						<div class="row">
							<div class="col">
								<div class="home_content text-center">
									<div class="home_logo"><img src="~/Content/images/home_logo.png" alt=""></div>
									<div class="home_text">
										<div class="home_title">Complete Online Courses</div>
										<div class="home_subtitle">Maecenas rutrum viverra sapien sed fermentum. Morbi tempor odio eget lacus tempus pulvinar. Praesent vel nisl fermentum, gravida augue ut, fermentum ipsum.</div>
									</div>
									<div class="home_buttons">
										<div class="button home_button"><a href="#">learn more<div class="button_arrow"><i class="fa fa-angle-right" aria-hidden="true"></i></div></a></div>
										<div class="button home_button"><a href="#">see all courses<div class="button_arrow"><i class="fa fa-angle-right" aria-hidden="true"></i></div></a></div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>


<!-- Courses -->
<div class="container mt-5">
        <h2 style="text-align:center;margin-top:40px;font-weight:bold">Latest Courses and Videos</h2>
        <div class="row justify-content-center mb-3">
            <div class="col-md-12 col-xl-10">
			@foreach (var item in Model)
                {
                    <div class="card shadow-0 border rounded-3 mb-4">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12 col-lg-3 col-xl-3 mb-4 mb-lg-0">
                                    <div class="bg-image hover-zoom ripple rounded ripple-surface">
									<img src="@item.CourseImage" class="w-100" />
                                        <a href="your-url.html">
                                            <div class="hover-overlay">
                                                <div class="mask" style="background-color: rgba(253, 253, 253, 0.15);"></div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                                <div class="col-md-6 col-lg-6 col-xl-6">
								<h5>@item.CourseName</h5>
                                    <div class="mt-1 mb-0 text-muted small">
									<span>@item.InstructorName</span>
                                    </div>
                                    <p class="text-truncate mb-4 mb-md-0">
									<br />
                                    </p>
                                </div>
                                
                                    <div class="col-md-6 col-lg-3 col-xl-3 border-sm-start-none border-start">
                                        <div class="d-flex flex-row align-items-center mb-1">
                                            <h4 class="mb-1 me-1">Price</h4>
                                            <span class="text-danger">₹ </span>
                                        </div>
                                        <h6 class="text-success">Special Offer</h6>
                                        <div class="d-flex flex-column mt-4">
									<a asp-controller="Userdashboard" asp-action="SubCourseList" asp-route-id="@item.CourseId" class="btn btn-warning">Course List</a>

                                            <button class="btn btn-outline-danger mt-2" type="button">Add to wishlist</button>
                                        </div>
                                    </div>
                              
                                   
                                
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>

        <div class="button home_button" style="margin-left:550px;margin-bottom:50px">
            <a asp-controller="Userdashboard" asp-action="AllCourse">See All Courses
                <div class="button_arrow"><i class="fa fa-angle-right" aria-hidden="true"></i></div>
            </a>
        </div>
    </div>





<!-- Milestones -->

<div class="milestones">
	@* <!-- Background image artis https://unsplash.com/@thepootphotographer --> *@
	<div class="parallax_background parallax-window" data-parallax="scroll" data-image-src="~/Content/images/milestones.jpg" data-speed="0.8"></div>
	<div class="container">
		<div class="row milestones_container">

			<!-- Milestone -->
			<div class="col-lg-3 milestone_col">
				<div class="milestone text-center">
					<div class="milestone_icon"><img src="~/Content/images/milestone_1.svg" alt=""></div>
					<div class="milestone_counter" data-end-value="1548">0</div>
					<div class="milestone_text">Online Courses</div>
				</div>
			</div>

			<!-- Milestone -->
			<div class="col-lg-3 milestone_col">
				<div class="milestone text-center">
					<div class="milestone_icon"><img src="~/Content/images/milestone_2.svg" alt=""></div>
					<div class="milestone_counter" data-end-value="7286">0</div>
					<div class="milestone_text">Students</div>
				</div>
			</div>

			<!-- Milestone -->
			<div class="col-lg-3 milestone_col">
				<div class="milestone text-center">
					<div class="milestone_icon"><img src="~/Content/images/milestone_3.svg" alt=""></div>
					<div class="milestone_counter" data-end-value="257">0</div>
					<div class="milestone_text">Teachers</div>
				</div>
			</div>

			<!-- Milestone -->
			<div class="col-lg-3 milestone_col">
				<div class="milestone text-center">
					<div class="milestone_icon"><img src="~/Content/images/milestone_4.svg" alt=""></div>
					<div class="milestone_counter" data-end-value="39">0</div>
					<div class="milestone_text">Countries</div>
				</div>
			</div>

		</div>
	</div>
</div>







<!-- Video -->
<h1 style="text-align:center;margin:40px 0px">Watch us to Know More</h1>
<div class="video">
	<div class="container">
		<div class="row">
			<div class="col">
				<div class="video_container_outer">
					<div class="video_container">
						<iframe id="vid1" src="https://www.youtube.com/embed/KLOcj5qvOio?autoplay=1&mute=1" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Join -->

<div class="join">
	<div class="container">
		<div class="row">
			<div class="col-lg-10 offset-lg-1">
				<div class="section_title text-center"><h2>Join Our Platform Today</h2></div>
				<div class="section_subtitle">Suspendisse tincidunt magna eget massa hendrerit efficitur. Ut euismod pellentesque imperdiet. Cras laoreet gravida lectus, at viverra lorem venenatis in. Aenean id varius quam. Nullam bibendum interdum dui, ac tempor lorem convallis ut</div>
			</div>
		</div>
	</div>
</div>